### ISSUE TITLE
failed to run benchmark_gym.py dqn2015 CartPole-v0

### ISSUE THREAD

**Issue by bettermanlu** [reinforceio/tensorforce-benchmark#1]
E:\uiuc\prj_TR\tensorforce-benchmark-master>e:\Python36\python scripts\benchmark_gym.py dqn2015 CartPole-v0
INFO:root:Running benchmark with 1 experiments
INFO:gym.envs.registration:Making new env: CartPole-v0
INFO:root:Starting experiment 1
Experiment 1:   0%|                                                      | 0/15000 [00:00<?, ?it/s]2
017-11-29 00:22:10.394262: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\pl
atform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but
these are available on your machine and could speed up CPU computations.

Traceback (most recent call last):
  File "scripts\benchmark_gym.py", line 200, in <module>
    sys.exit(main())
  File "scripts\benchmark_gym.py", line 169, in main
    save_model_file=args.model
  File "e:\uiuc\prj_tr\tensorforce-benchmark-master\tensorforce_benchmark\benchmark\runner\benchmark
_runner.py", line 216, in run
    results = self.run_experiment(environment, i)
  File "e:\uiuc\prj_tr\tensorforce-benchmark-master\tensorforce_benchmark\benchmark\runner\tensorfor
ce.py", line 107, in run_experiment
    episode_finished=self.episode_finished)
  File "e:\uiuc\prj_tr\tensorforce-master\tensorforce\execution\runner.py", line 96, in run
    action = self.agent.act(states=state, deterministic=deterministic)
  File "e:\uiuc\prj_tr\tensorforce-master\tensorforce\agents\agent.py", line 190, in act
    self.current_states[name] = preprocessing.process(state=self.current_states[name])
  File "e:\uiuc\prj_tr\tensorforce-master\tensorforce\core\preprocessing\preprocessing.py", line 44,
 in process
    state = processor.process(state=state)
  File "e:\uiuc\prj_tr\tensorforce-master\tensorforce\core\preprocessing\image_resize.py", line 36,
in process
    return scipy.misc.imresize(arr=state.astype(np.uint8), size=self.size)
  File "e:\Python36\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "e:\Python36\lib\site-packages\scipy\misc\pilutil.py", line 554, in imresize
    im = toimage(arr, mode=mode)
  File "e:\Python36\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "e:\Python36\lib\site-packages\scipy\misc\pilutil.py", line 326, in toimage
    raise ValueError("'arr' does not have a suitable array shape for "
ValueError: 'arr' does not have a suitable array shape for any mode.

**Comment by michaelschaarschmidt** [comment]
You are using a CNN inclusive image processing for a non-visual input. This cannot work.

**Comment by bettermanlu** [comment]
Hi Michael, 
Sorry, I am newbie. Could you let me know the correct way to run the benchmark for dqn2015?
Thanks.

**Comment by krfricke** [comment]
@bettermanlu you can either use the dqn2015 config for any Atari environment, e.g. `python scripts/benchmark_gym.py dqn2015 Pong-v0`. Or you use another config, e.g. you can start with https://github.com/reinforceio/tensorforce/blob/master/examples/configs/dqn.json and run that with `CartPole-v0`.

**Comment by bettermanlu** [comment]
thanks，I will give it a try.
