### ISSUE TITLE
Using Docker documentation not working

### ISSUE THREAD

**Issue by adrienrenaud** [reinforceio/tensorforce-benchmark#4]
Following the documentation in the readme (https://github.com/reinforceio/tensorforce-benchmark): 
```bash
$ docker pull reinforceio/tensorforce-benchmark:latest-gpu
$ nvidia-docker run -v /host/configs:/configs -v /host/output:/benchmarks reinforceio/tensorforce-benchmark:latest-gpu my_config CartPole-v0
Traceback (most recent call last):
  File "scripts/benchmark_gym.py", line 200, in <module>
    sys.exit(main())
  File "scripts/benchmark_gym.py", line 169, in main
    save_model_file=args.model
  File "/tensorforce-benchmark/tensorforce_benchmark/benchmark/runner/benchmark_runner.py", line 209, in run
    max_episodes = self.config.get('max_episodes')
AttributeError: 'NoneType' object has no attribute 'get'
```

Could you update the documentation so that we can have a working example? Thanks

**Comment by krfricke** [comment]
Thanks for your message and for raising the issue. I updated the docker images and it should be working now (it did for me).
